version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/"
    labels:
      - "dependencies"
    groups:
      python-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    labels:
      - "dependencies"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
