repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        name: EOF fixer
      - id: trailing-whitespace
        name: Trailing Whitespace fixer

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.10
    hooks:
      - id: uv-lock
        name: Make uv Lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: Ruff check fix
        args: [ --fix ]
      - id: ruff-format
        name: Ruff format

  - repo: local
    hooks:
      - id: just-fmt
        name: Format Justfile
        entry: just --unstable --fmt
        language: system
        files: Justfile$
        pass_filenames: false
