x-default: &default
  restart: "no"

services:
  migration:
    <<: *default
    image: $LOCAL_IMAGE
    container_name: fastapi-lambda_migration
    env_file:
      - .env.local
    command: ["uv", "run", "alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy

  api:
    <<: *default
    image: $LOCAL_IMAGE
    container_name: fastapi-lambda_api
    env_file:
      - .env.local
    ports:
      - "8080:8000"
    depends_on:
      migration:
        condition: service_completed_successfully
