name: "Static check"
on:
  push:
    branches: [master]
    paths:
      - "**/*.py"
  pull_request:
    branches: [master]
    paths:
      - "**/*.py"
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy .
